ENT.Base 			= "npc_vj_creature_base"
ENT.Type 			= "ai"
ENT.PrintName 		= "Zombie Shelter Zombie Base AI"
ENT.Author 			= "Meiryi"
ENT.Contact 		= ""
ENT.Purpose 		= "Fuck VJ Base"
ENT.Instructions 	= ""
ENT.Category		= ""