ENT.Base 			= "npc_vj_zshelter_sentry"
ENT.Type 			= "ai"
ENT.PrintName 		= "ZShelter Mortar Cannon"
ENT.Author 			= "Meika"
ENT.Contact 		= ""
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "ZShelter"