ENT.Base 			= "base_gmodentity"
ENT.Type 			= "anim"
ENT.PrintName 		= "ZShelter Mortar Cannon Missile"
ENT.Author 			= "Meika"
ENT.Contact 		= ""
ENT.Purpose 		= ""
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "ZShelter"